# Generated by Django 2.2.1 on 2019-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField()),
                ('accommodation_type', models.TextField(max_length=300)),
                ('hotel_name', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=1000)),
                ('district', models.TextField(max_length=300)),
                ('country', models.TextField(max_length=100)),
                ('thumb_urls', models.TextField(max_length=5000)),
                ('star_rating', models.FloatField()),
                ('guest_rating', models.FloatField()),
                ('review_badge', models.TextField(max_length=100)),
                ('hotel_price', models.TextField(max_length=50)),
            ],
        ),
    ]
