# Generated by Django 2.2.1 on 2020-01-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='month',
            new_name='date_time_month',
        ),
        migrations.RenameField(
            model_name='userinteraction',
            old_name='year',
            new_name='date_time_year',
        ),
    ]
